services:
  node-red:
    container_name: node-red
    image: nodered/node-red:4.1-debian
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data
  
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    environment:
      - TZ=America/New_York
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - NET_ADMIN

volumes:
  node-red-data: