services:
  ollama:
    image: ollama/ollama:0.9.3-rocm
    ports:
      - 11434:1143
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]