services:
  ollama:
    image: ollama/ollama:0.9.3-rocm
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  webui-ollama:
    image: ghcr.io/open-webui/open-webui:v0.6.15
    volumes:
      - ./webui:/app/backend/data
    ports:
      - 8080:8080
    # extra_hosts:
    #   - host.docker.internal:host-gateway #docker
    #   - host.containers.internal:host-gateway #podman