services:
  data-science-stack:
    build: ./dockerfiles
    image: data-science-stack:0.0
    working_dir: /project
    environment:
      - JUPYTER_PORT=8888
      - DOCKER_STACKS_JUPYTER_CMD=lab
      # - NOTEBOOK_ARGS=--ip 0.0.0.0
    volumes:
      - ./config/jupyter_lab_config.py:/home/jovyan/.jupyter/jupyter_lab_config.py:ro
      - ./config/jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py:ro
      - ./project:/project
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.1
    ports:
      - 5000:5000
    # environment:
    #   - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    #   - AWS_ACCESS_KEY_ID=minioadmin
    #   - AWS_SECRET_ACCESS_KEY=minioadmin