services:
  data-science-stack:
    build: ./
    image: data-science-stack:0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]