services:
  data-science-stack:
    build: ./
    image: data-science-stack:0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.1
    ports:
      - 5000:5000
    # environment:
    #   - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    #   - AWS_ACCESS_KEY_ID=minioadmin
    #   - AWS_SECRET_ACCESS_KEY=minioadmin