services:
  influxdb:
    image: influxdb:2.7.12
    # image: influxdb:3.2.0-core
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb3
      - ./influxdb/config:/etc/influxdb3
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=qwerasdf
      - DOCKER_INFLUXDB_INIT_ORG=my-organization
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket-data
      
  grafana:
    image: grafana/grafana:12.0.2-ubuntu
    environment:
    #  - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=qwerasdf
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana